{{- $serviceName := include "name" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}-{{ .Values.azureVoteFront.deployment.name }}
  labels:
{{ include "labels.standard" . | indent 4 }}
    component: {{ $serviceName }}-{{ .Values.azureVoteFront.deployment.name }}
spec:
  selector:
    matchLabels:
{{ include "labels.standard" . | indent 8 }}
        component: {{ $serviceName }}-{{ .Values.azureVoteBack.deployment.name }}
  replicas: {{ .Values.azureVoteFront.deployment.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
{{ include "labels.standard" . | indent 8 }}
        component: {{ $serviceName }}-{{ .Values.azureVoteFront.deployment.name }}
    spec:
      containers:
      - name: {{ $serviceName }}-{{ .Values.azureVoteFront.deployment.name }}
        image: "{{ .Values.azureVoteFront.deployment.image }}:{{ .Values.azureVoteFront.deployment.imageTag }}"
        imagePullPolicy: {{ .Values.azureVoteFront.deployment.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.azureVoteFront.deployment.internalPort }}
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ $serviceName }}-azure-vote
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ $serviceName }}-azure-vote
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ $serviceName }}-azure-vote
              key: MYSQL_DATABASE
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: {{ $serviceName }}-azure-vote
              key: MYSQL_HOST
        resources:
{{ toYaml .Values.azureVoteFront.deployment.resources | indent 10 }}